source/.res/code/db.get-sibling-db.create-user.txt, source/.res/replace.txt, source/conf-mongodb.rst, source/conf-mysql-requirements.rst
GRANT command wrong here:
https://www.percona.com/doc/percona-monitoring-and-management/2.x/concepts/services-mysql.html#pmm-conf-mysql-user-account-creating
=> PMM-5707 GRANT command incorrect

source/release-notes/index.rst
=> PMM-5732 RN (2)

source/release-notes/2.5.0.rst
=> PMM-5732 RN 3 - Clarify that both PMM Client and Server were changed

source/manage/index-using-pmm-client.rst
Repeat change to add client annotations, avoiding clash of release/version.
=> PMM-5559 New branch to avoid wrong version in conf

source/.res/replace.txt, source/manage/server-admin-gui.rst
Repeat of previous retracted PR.
=> PMM-5820 Admonish reader that STT requires instant telemetry

source/platform/stt.rst
https://confluence.percona.com/display/PMM/Security+Threat+Tool+checks
=> update according  latest changes from

source/manage/client-annotations.rst, source/manage/index-using-pmm-client.rst, source/reference/pmm-admin.rst
Complete rework of annotations section. Update of pmm-admin man page. Removal of missing files from index (to reduce Sphinx warnings).
=> PMM-5563 annotations

source/conf-mysql-requirements.rst, source/faq.rst, source/manage/server-admin-gui.rst, source/manage/server-pmm-api.rst
Consolidated info for "What resolution is used for metrics?" FAQ item.
General improvements to readability for other FAQ items.
Reformatting reST to PMM standards.
=> PMM-5324 metrics resolution

source/install/client-install-apt.rst
Updated list of supported Linux.
Removed replacements, includes, asciicinema snippets.
Tidied and cleaned rst syntax according to style guidelines.
=> PMM-5697 Supported Ubuntu

source/_res/mongodb-requirements.rst, source/_res/mysql-requirements.rst, source/conf.py, source/dashboards/dashboard-mysql-overview.rst, source/dashboards/dashboard-node-memory.rst, source/dashboards/dashboard-node-summary.rst, source/install/docker-setting-up.rst, source/release-notes/2.0.1.rst, source/release-notes/2.1.0.rst, source/release-notes/2.2.0.rst, source/release-notes/2.2.1.rst, source/release-notes/2.2.2.rst, source/release-notes/2.3.0.rst
Remove unused Sphinx extensions or make them redundant with alternatives.
Cleanup of conf.py and consequences in source files.
=> PMM-5985 standard sphinx extensions

source/_res/mysql-requirements.rst, source/concepts/architecture.rst, source/dashboards/dashboard-inventory.rst, source/dashboards/dashboard-mysql-amazon-aurora-metrics.rst, source/install/aws.rst, source/install/client-install-yum.rst, source/manage/client-annotations.rst, source/manage/server-admin-gui.rst, source/platform/stt.rst
Convert file, code, program and command roles to normal inline code.
Convert guilabel and menuselection to italics.
=> PMM-6039 inline code

docs/manage/client-mongodb-ssl.md, source/conf.py, source/manage/client-mongodb-ssl.rst
Update of MongoDB SSL info with available params taken from 'pmm-admin add mongodb --help'
=> PMM-6476 mongodb ssl

docs/manage/conf-postgres.md, docs/reference/pmm-admin.md, source/manage/conf-postgres.rst, source/reference/pmm-admin.rst
Will create md version when rst reviewed and done
=> PMM-6464 new pg-stat-monitor extension

docs/faq.md, source/faq.rst
Add information about access to exporter
=> PMM-6808  Add information about exporter date troubleshoot 

docs/manage/security.md, mkdocs-pdf.yml, mkdocs-preview.yml, mkdocs.yml
Combined into generic 'security' section (to be expanded).
=> PMM-5074 ssl certificates

docs/reference/pmm-admin.md
Open question whether this should be wait or timeout.
=> PMM-6820 pmm-admin status --wait (New flag)

docs/details/index.md, docs/details/victoria-metrics.md, docs/faq.md, mkdocs-pdf.yml, mkdocs.yml
New section for VictoriaMetrics reference information. A FAQ item was moved here.
=> PMM-6777 victoriametrics

docs/details/commands/pmm-agent.md, docs/details/index.md, mkdocs.yml
Added mainly to find a home for questions/information about logging (such as https://forums.percona.com/discussion/comment/57970).
(The content is based on the output of `pmm-agent --help-man`.)
@adivinho Please check the bottom 'LOGGING' section. Also suggest some usage examples and add other experts for review, thanks.
=> pmm-agent man page

docs/using/platform/dbaas.md
Reviewers: Please check wording of bottom-most alert
=> PMM-6899 External connection

docs/using/alerting.md, docs/using/platform/dbaas.md, icon.yml, mkdocs.yml
HTML icons as variables for convenience.
=> Icons use macro variables

docs/setting-up/client/docker.md
Some tips on how to reference Dockerized PMM server by container name
=> Reference Dockerized PMM server by container name

docs/setting-up/server/dbaas.md
Please see https://jira.percona.com/browse/PMM-7404 understand the reason to do this.
=> PMM-7404 Updating minikube supported version

docs/using/platform/security-threat-tool.md
https://jira.percona.com/browse/PMM-7328
=> PMM-7328 Update STT docs

docs/details/commands/pmm-admin.md, docs/details/commands/pmm-agent.md
https://jira.percona.com/browse/PMM-7306
=> PMM-7306 Add description of disable collectors flag.

docs/details/commands/pmm-admin.md
=> Revert "PMM-5888 Help improvements for pmm-admin."

docs/details/commands/pmm-admin.md, docs/details/commands/pmm-agent.md
=> Revert "PMM-7306 Add description of disable collectors flag."

docs/setting-up/client/mysql.md
=> Pmm 7105 mariadb

docs/setting-up/client/index.md
Some versions are not supported anymore according to https://www.percona.com/services/policies/percona-software-support-lifecycle#pt
=> Update index.md to remove EOL'ed OS versions

docs/faq.md, docs/how-to/configure.md, docs/how-to/upgrade.md, docs/setting-up/client/index.md, docs/setting-up/server/docker.md, docs/setting-up/server/index.md
No new info but existing stuff was scattered and has been grouped into the most logical places in the reader's journey from 'Welcome' through 'Setting up'.
=> PMM-5952 Reorganise sysreqs sections

docs/setting-up/server/dbaas.md
Fix sed for EKS too. We did this for minikube already.
@PaulJacobs-percona meabe we can somehow merge these intructions so we don't modify only one in the future. What do you think?
=> DBaaS: fix sed for eks

.gitignore, mkdocs-netlify.yml, mkdocs.yml, nav.yml
Separate mkdocs config file for standard theming. Navigation element now common.
=> Separate config for netlify test

docs/how-to/configure.md
Warn that turning DBaaS off doesn't affect cluster status.
=> PMM-7820 DBaaS on/off warning

docs/using/alerting.md
WIP: Need exact list of disallowed 'special' chars in templates.
=> PMM-7700 Alerting template restrictions

docs/setting-up/server/dbaas.md, docs/using/index.md, docs/using/platform/dbaas.md, docs/using/platform/index.md
to be consistent with https://www.percona.com/doc/percona-monitoring-and-management/2.x/using/alerting.html message
=> Change DBaaS status from  Alpha to TechPreview

.github/workflows/build.yml, README.md
The badge is no longer necessary.
=> remove fossa's badge

docs/details/commands/pmm-admin.md
https://jira.percona.com/browse/PMM-6553
ref: percona/pmm-managed#754
FB: Percona-Lab/pmm-submodules#1750
=> PMM-6553 Fix slow log size unit

docs/setting-up/server/dbaas.md, docs/using/platform/dbaas.md
Operators are now installed automatically on cluster registration in DBaaS.
=> PMM-6432 install operators on k8s registration

_resources/bin/remove-contractor-thanks.sh, docs/release-notes/2.18.0.md, docs/release-notes/index.md, mkdocs-pdf.yml, mkdocs-percona.yml, mkdocs.yml
Preview: https://60ad1f89a3149c0008de2464--pmm-doc-preview.netlify.app/release-notes/2.18.0.html
=> RM-924 RN 2.18.0

docs/details/dashboards/index.md, docs/js/table.number.js, docs/js/tables.js, mkdocs-pdf.yml, mkdocs-percona.yml, mkdocs.yml
First use in Dashboards reference home page.
=> Sortable tables

docs/how-to/troubleshoot.md, docs/using/query-analytics.md
https://jira.percona.com/browse/PMM-5283
=> PMM-5283 Truncate query example and fingerprint

docs/setting-up/server/easy-install.md
We need to merge checksum before this PR: https://github.com/percona/pmm/pull/756
=> PMM-8278 add SHA256 hash to oneline script

docs/details/commands/pmm-admin.md
Reverts percona/pmm-doc#541
Meant for 2.20.0 only.
=> Revert "Pmm 7010 pmm admin unregister"

docs/details/architecture.md, docs/details/commands/pmm-admin.md, docs/details/commands/pmm-agent.md, docs/details/index.md, docs/details/interface.md, docs/how-to/configure.md, docs/how-to/optimize.md, docs/how-to/troubleshoot.md, docs/setting-up/client/google.md, docs/setting-up/client/haproxy.md, docs/setting-up/client/index.md, docs/setting-up/client/mongodb.md, docs/setting-up/client/mysql.md, docs/setting-up/client/postgresql.md, docs/setting-up/index.md, docs/setting-up/server/aws.md, docs/setting-up/server/dbaas.md, docs/setting-up/server/docker.md, docs/setting-up/server/network.md, docs/using/backup.md, docs/using/dbaas.md, docs/using/index.md, docs/using/interface.md, docs/using/security-threat-tool.md
Attempt to properly punctuate lists and elsewhere.
=> PMM-8111 Consistent punctuation (mainly lists)

docs/using/backup.md
Preview https://60f14ea19c301300070ab668--pmm-doc.netlify.app/using/backup.html#delete-a-backup
=> PMM-8158 Delete backup

docs/using/alerting.md
Improvements to address some confusion on what is optional vs mandatory, and general clarifications.
Preview: https://pmm-8536-integrated-alerting-improvements--pmm-doc.netlify.app/using/alerting.html
=> PMM-8536 Rework Integrated Alerting page

docs/setting-up/client/aws.md
Adds documentation on creating IAM roles to be able to add Amazon RDS instances.
https://jira.percona.com/browse/PMM-7690
=> PMM-7690 IAM roles

docs/release-notes/2.21.0.md
feel free to tag others to fill in the conent...but we really shouldn't need a complicated process to get the word out...please do not overthink it...
=> Give users easier access to the workaround for broken upgrade

docs/setting-up/server/docker.md
Feedback from Ananias that the Disable Updates env flag is confusing so attempting to make it less so.
=> make update check wording less confusing

docs/release-notes/2.24.0.md
=> Update 2.24.0 with RN Highlights 

docs/release-notes/2.24.0.md, docs/release-notes/index.md, mkdocs-base.yml, variables.yml
https://jira.percona.com/browse/RM-972
https://deploy-preview-622--pmm-doc.netlify.app/release-notes/2.24.0.html
Release highlights PR - https://github.com/percona/pmm-doc/pull/625
=> RM-972 Release Notes 2.24.0

docs/using/alerting.md
Ticket: https://jira.percona.com/browse/PMM-8993
=> PMM-8993: Require SMTP TLS flag

docs/details/advisors/checks/security-anonymous-user.md, docs/details/advisors/checks/security-non-root-accounts-super-privileges.md, docs/details/advisors/checks/security-user-not-using-ssl-protocol.md, docs/details/advisors/checks/security-user-with-open-to-the-word-scope.md, docs/details/advisors/checks/security-user-without-password.md
@rnovikovP can u take a look and see if is ok to merge in respect to what we had discussed?
=> Adding mine security docs

docs/details/advisors/checks/configuration-pg-check-fsync-enabled.md, docs/details/advisors/checks/configuration-pg-high-max-connections.md, docs/details/advisors/checks/configuration-pg-log-autovacuum-disabled.md, docs/details/advisors/checks/configuration-pg-log-checkpoints-disabled.md, docs/details/advisors/checks/configuration-pg-settings-changed.md, docs/details/advisors/checks/performance-pg-archiver-failing.md, docs/details/advisors/checks/performance-pg-low-cache-hit-ratio.md, docs/details/advisors/checks/performance-pg-stale-replication-slot.md
I've added the documentation files for the PG advisors v1
=> Adding documentation to PG advisors v1

docs/how-to/upgrade.md, docs/setting-up/client/index.md
Add instruction how to update PMM2-Agent without rewriting config file
=> PMM-8867 How to update pmm2-client

docs/setting-up/server/docker.md
Stopping the docker container was missing in the steps for the upgrade. Added the stop action.
=> Added stop action while upgrade

docs/details/api.md
Update the document with the steps to generate and use API keys...
=> PMM-9375-explaning-api-keys

docs/how-to/configure.md, docs/release-notes/2.26.0.md, docs/release-notes/index.md, docs/using/alerting.md
Added description for Test Email Configuration and improved the current structure of the "Set up a communication channel" topic.
=> Added changes for Test Email option

docs/setting-up/server/docker.md
we are not officially supporting it, for now, so useless step
=> Remove docker compose

docs/setting-up/server/easy-install.md
added instructions for using wget (curl not part of ubuntu default install)
Added information about interactive mode for users that want to customize installation parameters from our defaults
=> added wget and highlight other mode

docs/how-to/configure.md, docs/using/security-threat-tool.md
Updated info about the security threat tool (PMM-9382)
=> Security checks

docs/details/advisors/checks/configuration-innodb-file-format.md, docs/details/advisors/checks/configuration-innodb-flush-method.md
as for PMM-9578 this is to fix the wrong read-more doc
=> Fixing the wrong read-more description for File-format and Flush methods

docs/details/advisors/checks/configuration-innodb-file-format.md, docs/details/advisors/checks/configuration-innodb-flush-method.md
Suggestions to improve readability
=> Linguistic review for PMM 9578

docs/faq.md, docs/setting-up/server/docker.md
Change the password for the default admin user.
=> Pmm 9452 change admin user password3

docs/using/dbaas.md
Added a warning before creating a Kubernetes Cluster to add the Public IP address in settings
=> PMM-9562 warning public IP address Kubernetes

docs/faq.md, docs/setting-up/server/virtual-appliance.md
Change the default password for PMM when using the OVF installation.
=> PMM-9542 change default password

docs/setting-up/server/docker.md
Added  new environment variable PMM_PUBLIC_ADDRESS.
=> PMM-8434 new variable for pmm public address

docs/release-notes/1.17.5.md, docs/release-notes/index.md, mkdocs-percona.yml, mkdocs.yml, variables.yml
=> Release Notes 1.17.5

docs/release-notes/1.17.5.md
Updating PMM 1.17.5 Release Notes with EOL and security release information
=> Pmm1 release notes 1 17 5 updates

docs/release-notes/1.17.5.md
=> Revert "Pmm1 release notes 1 17 5 updates"

mkdocs-base.yml, variables.yml
Make changes to the version and config changes for PMM release 2.27.0
=> Version changes and config changes for PMM 2.27.0

docs/setting-up/client/mysql.md
Modified the CREATE DATABASE command for MySQL 5.7
=> PMM-9331 mysql commands for user creation

docs/index.md
Update the welcome page as per feedback from marketing...
=> Update welcome page as per feedback

.gitignore, build.sh, docs/release-notes/1.17.5.md, docs/release-notes/index.md, mkdocs-percona.yml, mkdocs.yml, variables.yml
=> PMM1 Release version 1.17.5

.github/workflows/build.yml, docs/release-notes/1.17.5.md, docs/release-notes/index.md
=> PMM1 Rel 1.17.5 Updates

docs/using/interface.md
This is what it looks like before the fix
=> Fix the broken alert

mkdocs-base.yml, mkdocs-percona.yml, mkdocs.yml, theme/404.html
This implements two features:
- a basic 404 page (design can be improved)
- a dark/light mode toggle
=> PMM-0000 create a custom 404 page

docs/setting-up/client/index.md
Added Support for Ubuntu 22.04 LTS for PMM Client
=> PMM-9907 added support for Ubuntu 22.04 LTS

docs/how-to/configure.md, docs/how-to/troubleshoot.md
PMM logs added to the help menu.
=> PMM-9958 PMM logs added to help

docs/setting-up/server/dbaas.md
https://jira.percona.com/browse/PMM-7
Build: https://github.com/Percona-Lab/pmm-submodules/pull/2511
=> update dbaas tools

docs/details/commands/pmm-admin.md
Added credentials-source flag which can be used instead of username and password flags.
=> PMM-9590 credentials source flag

docs/details/clickhouse.md, docs/details/index.md, docs/setting-up/server/docker.md, mkdocs-base.yml
Ability to use external ClickHouse database instance for PMM server.
=> PMM-9354 external clickhouse DB instance

docs/setting-up/server/docker.md
https://jira.percona.com/browse/PMM-9627
=> PMM-9627 add k8s env

docs/details/commands/pmm-admin.md
=> Revert "PMM-9590 credentials source flag"

.github/workflows/helm-tests.yml, docs/setting-up/index.md, docs/setting-up/server/helm.md, docs/setting-up/server/index.md, mkdocs-base.yml
https://jira.percona.com/browse/PMM-9613
=> add helm documentation

.github/workflows/helm-tests.yml, .github/workflows/podman-tests.yml, _resources/bin/CodeBlock.lua, _resources/bin/doc_test_template.sh, docs/setting-up/index.md, docs/setting-up/server/helm.md, docs/setting-up/server/index.md, docs/setting-up/server/podman.md, mkdocs-base.yml
https://jira.percona.com/browse/PMM-7925
=> PMM-7925: PMM regular user server deployment using Podman [Technical Preview]

docs/how-to/configure.md
to make a list aligned with https://github.com/percona/pmm/blob/main/managed/services/telemetry/config.default.yml
=> PMM-10119 Update the list of metrics collected

docs/details/commands/pmm-admin.md
New parameters added for pmm-admin command
=> New parameters pmm admin command

docs/release-notes/index.md, mkdocs-base.yml, variables.yml
Config changes for version PMM 2.29.1
=> PMM-10390-Config_changes_2.29.1

docs/release-notes/2.29.1.md
Fix for CVE impacting Alerting.
=> PMM-10338 fixed CVE for 2.29.1

docs/using/alerting.md
Fixed the issue for double quotes.
=> Fixed quotes

docs/setting-up/server/dbaas.md
=> Revert "PMM-10018 set default haproxy resources"

docs/index.md
Add G2 tracking pixel to PMM doc index.html as per the ticket: 
https://percona.atlassian.net/servicedesk/customer/portal/2/HD-17398
=> HD-17398 Add G2 Tracking pixel

docs/how-to/troubleshoot.md
Improving the resolving issues section.
=> Resolving Issues section improvements

docs/setting-up/index.md
=> remove tech preview from podman

mkdocs.yml
https://jira.percona.com/browse/DOCS-55
=> DOCS-55-update-site-url-value

docs/details/commands/pmm-admin.md
=> PMM-11029 Known issue QAN

mkdocs-base.yml
=> Config-changes-PMM-2.32.0

docs/release-notes/2.32.0.md
Was reading release notes and saw a typo.
=> Fix typo in description

docs/using/backup.md, docs/using/mongodb_limitations.md
and  change the order of tech . (Mongo first  as GA )
=> Clarification about Tech preview for MySQL

docs/release-notes/2.32.0.md, docs/using/backup.md, docs/using/mongodb_limitations.md
Replace S3  with S3 compatible
=> Update RN and Backup documentation about S3 compatible storages support 

docs/release-notes/2.32.0.md
Fix some typos in the v2.32 release notes page.
=> v2.32 release notes typos

docs/setting-up/server/podman.md
=> Add 2.32 release to the docs

docs/setting-up/server/docker.md
DATA_RETENTION env variable can only be expressed in hours #1620
=> GITHUB-1620 Data Retension format

docs/get-started/dbaas.md
2.32.0 is used despite the latest version now being 2.34.0
=> Update PMM version used in helm examples

docs/release-notes/2.35.0.md
- Missing "for more information" links for DBaaS backup and restore. Now added --> will help users learn more about this feature
- Removed unclear `
**Before:**
**Now:**
Thanks,
=> Release notes v2.35.0 - improvements

docs/get-started/query-analytics.md
We show the ranges also in the image, no need to list them in text
=> Delete "Ranges" section that just shows list of range values

docs/get-started/alerting.md
"required field" -> "required"
=> Consistency in language usage

docs/details/postgresql.md, docs/setting-up/server/docker.md
[PMM-11438](https://jira.percona.com/browse/PMM-11438)
Build: [PMM-10913](https://github.com/Percona-Lab/pmm-submodules/pull/2965)
=> PMM-11438-stop-internal-postgresql-server

docs/setting-up/server/docker.md
Please review for the correctness of what I wrote there too. "Ignored variables" was misleading. I merged those in a single section and explained that subset won't be check for correctness.
=> Clarify what ignored env variables mean.

docs/details/postgresql.md, docs/setting-up/server/docker.md
[Ticket](https://jira.percona.com/browse/PMM-11951)
[PR](https://github.com/percona/pmm/pull/1521)[
Build](https://github.com/Percona-Lab/pmm-submodules/pull/3185)
=> PMM-11951-documentation-for-external-postgres

overrides/main.html
Updated Google Tag Manager in the doc template.
=> Updated the script for Google Analytics

mkdocs-base.yml, overrides/main.html, requirements.txt
modified:   mkdocs-base.yml
modified:   overrides/main.html
modified:   requirements.txt
=> Adding text snippets to link previews

docs/release-notes/2.37.1.md, docs/release-notes/index.md, mkdocs-base.yml, variables.yml
1. Create RN for PMM 2.37.1
2. Update the index file
3. Update the config file
=> Release Notes PMM 2.37.1

docs/setting-up/client/mysql.md
https://jira.percona.com/browse/PMM-11161
=> PMM-11161 Wrong mysql create user statement for pmm

mkdocs-base.yml, requirements.txt
=> Revert "remove meta description plugin"

docs/release-notes/2.37.0.md
revert PMM-4466 migrate to Postgres from SQLite from 2.37.0 Release Notes
=> revert PMM-4466 migrate to Postgres from SQLite from RN

mkdocs-base.yml
Remove the light gallery extension as PDF is not building.
=> remove_lightgallery_extn

docs/copyright.md, docs/trademark-policy.md, mkdocs-base.yml
new file:   docs/copyright.md
new file:   docs/trademark-policy.md
modified:   mkdocs-base.yml
=> DOCS-72 Add Trademark Policy, Copyright and Licensing Information (PMM)

docs/setting-up/client/mongodb.md
=> Update mongodb.md - typo fix

docs/dbaas/setting-up.md, docs/setting-up/server/docker.md
Rendered: https://pmm-doc-pr-1128.onrender.com/dbaas/setting-up.html#start-pmm-server-and-activate-a-dbaas-feature
=> PMM-12045 fix outdated change password instructions

docs/setting-up/server/docker.md
User suggested a hint that new docker container has newer CPU arch requirements.
=> Hint for new CPU arch requirements

docs/release-notes/2.39.0.md
Add the following improvement in the RN: https://jira.percona.com/browse/PMM-12389
=> Rn 2.39.0 updates

docs/setting-up/client/postgresql.md
Fixed the link to pg_stat_monitor_documentation
=> Fixed the link to pg_stat_monitor_documentation on  postgresql.md

docs/dbaas/architecture.md, docs/dbaas/databases.md, docs/dbaas/setting-up.md
Add warning to DBAAS pages to indicate their Tech Preview state
=> Dbaas tech preview

docs/setting-up/client/aws.md
For details see,
https://jira.percona.com/browse/PMM-10145
=> PMM-12430 aws rds cannot add instance

docs/details/victoria-metrics.md
For details see,
https://jira.percona.com/browse/PMM-9374
=> PMM-12410-VM-DB-instance

docs/release-notes/2.40.0.md
Fix the image links for RN for 2.40.0
=> Fixed the images links

docs/release-notes/2.37.1.md, docs/release-notes/2.40.0.md
Update the RN for the known issue for PMM 2.40.0.
=> 2.40.0_RN_update

docs/release-notes/2.40.1.md
update the relese notes for PMM 2.40.1
=> RN_updates_2-40.1

docs/release-notes/index.md, mkdocs-base.yml
Change the base of RN for 2.41.0 branch.
=> Release Notes 2.41.0 Base Branch change

docs/release-notes/2.41.1.md
PMM-12425
QAN picking different date range will cause an error
=> PMM-12425   QAN picking different date range will cause an error

docs/release-notes/2.41.1.md
PMM-12712
Collect Data about Sharded collections in MongoDB
=> PMM-12712   Collect Data about Sharded collections in MongoDB

docs/setting-up/client/mongodb.md
Follow-up of [PR 1194](https://github.com/percona/pmm-doc/pull/1194)
**Before:**
**Now:**
=> fix style issue by adding missing space

docs/get-started/query-analytics.md
https://perconadev.atlassian.net/browse/PMM-10974
=> PMM-10974 PGSM switch.

docs/get-started/query-analytics.md
This reverts commit e6d420257dd79bd3bcb7e9d46751adeb1fc0f9a9.
=> Revert "PMM-10974 PGSM switch. (#1216)"

docs/css/osano.css, docs/js/consent.js, mkdocs-base.yml, overrides/main.html, overrides/partials/copyright.html, snippets/services-banner.md
new file:   docs/css/osano.css
new file:   docs/js/consent.js
modified:   mkdocs-base.yml
modified:   overrides/main.html
new file:   overrides/partials/copyright.html
modified:   snippets/services-banner.md
=> DOCS-106 Implement Osano Cookie consent in docs.percona.com + remove scarf

docs/release-notes/2.41.2.md
Additional fixed issues to be added to the Release Notes for PMM 2.41.2.
=> Additional tickets to be added to RN for 2.41.2

mkdocs-base.yml
=> Remove copyright info from mkdocs-base.yml

overrides/main.html
modified:   overrides/main.html
=> PMM-13056 Add PostHog script and configure dashboards for PMM project

docs/index.md, mkdocs-base.yml, overrides/partials/header.html
modified:   docs/index.md
modified:   mkdocs-base.yml
modified:   overrides/partials/header.html
=> Fix links to repos

docs/setting-up/client/mysql.md
To remove the 5.7 EOL version and make the table smaller 
(better presentation - future scope )
=> Clarification on SlowLog vs P_S versions

mkdocs-base.yml
=> Remove the copyright script

docs/details/query-analytics.md, docs/get-started/query-analytics.md, mkdocs-base.yml
Ticket: https://perconadev.atlassian.net/browse/PMM-11278
=> PMM-11278 QAN under the hood.

mkdocs-base.yml
=> Revert "update logo for PDF"

docs/css/design.css
=> Fix table borders and code blocks (3.0.0)

docs/setting-up/client/mongodb.md
Fix updateRole command and warning not displayed properly.
Our current role is not providing data for other collections except for profile
=> Update MongoDB user permissions

docs/setting-up/client/index.md
added "-x86_64 "
For v2 I'm skipping the ARM as not officially supported for this version
=> PMM-13559   PMM client binary download link is broken

docs/details/commands/pmm-admin.md
Link to the specific FAQ, instead to the generic FAQ page.
=> Improve data retention link
