percona/pmm-doc

source/install/client-install-apt.rst
source/install/client-install-yum.rst

Fis for incorrect (outdated)  documentation in our Installation Manual 
This will be replaced by 
--server-url=https://admin:admin@<IP Address\>:443
Because for now, PMM requires HTTPS and username/password  (admin/admin  is the default )

PMM-5253 fix server url parameter presentation in pmm client config doc

---

source/manage/conf-mysql-perf-schema.rst

Added a note reminding that perf schema not enabled by default on MariaDB 10.x instances.

PMM-5627: Mention of perfschema in MariaDB 10.x

---

source/manage/client-proxysql-metrics.rst

Described use of `--socket` option and added example of using it (instead of `--port`).

PMM-5257 Add --socket option and example for proxysql

---

source/manage/client-mongodb-metrics.rst

Mentioned socket option using MySQL example as phrasing template.

PMM-5256 doc use of --socket option when adding MongoDB instance

---

docs/install/virtual-appliance.md
source/install/virtual-appliance.rst

Note: Sphinx/rst doesn't allow variables in URLs, so those download links are hard-coded with '2.9.1'. MkDocs does allow variables.

PMM-5994 Link to OVA downloads page

---

source/install/clients.rst

Was pointing to pmm-client which redirected to pmm1 but should point to pmm2 downloads, fixed

Fix link to download latest version of PMM

---

source/_templates/edit.html
source/conf.py

Linking to rst and md formats and moved towards top of left navbar.

Edit this page formats

---

mkdocs.yml
theme/main.html

Tests to make version picker switch to same domain
e.g. 
2->1 (test)
new.percona.com/doc/percona-monitoring-and-management/2.x/index.html -> new.percona.com/doc/percona-monitoring-and-management/index.html
2->1 (live)
www.percona.com/doc/percona-monitoring-and-management/2.x/index.html -> www.percona.com/doc/percona-monitoring-and-management/index.html
(1->2 doesn't work like this yet as URLs are hard-coded into PMM1's code for version switcher.)

Version picker test

---

theme/main.html

Web host is VERY strict about paths, not allowing even a stray slash in the URL.

Tweak paths for version switcher

---

docs/setting-up/client/proxysql.md

Documentation mentions MongoDB, uses the MySQL port and also talks about local database instances

Invalid information for ProxySQL monitoring

---

docs/using/alerting.md

There is no easy way to create an alert template as we provide no guide so until you can view/clone existing templates we need at least something on the website to help users create a template.  This doesn't even scratch the surface though of how to actually create an alert on something unique nor a guide to what the possible variables/substitutions are.

Adding an example alert template to documentation

---

docs/using/platform/dbaas.md

since we don't do any pre-validation, makes sense to tell the user up front how to know if they're k8s cluster has enough resources to start their desired DB cluster config.

configuration hint for resource consumption

---

docs/deploy/index.md

Fixed broken links to PMM server and client upgrade manual.
Before fix it looks like:
https://www.percona.com/doc/percona-monitoring-and-managemehttps://www.percona.com/doc/percona-monitoring-and-management/2.x/setting-up/
in this section
https://www.percona.com/doc/percona-monitoring-and-management/1.x/deploy/index.html#updating

Fixed broken links to manual

---

docs/setting-up/server/dbaas.md

The equal sign makes sed not work. The password is not included in the secret and user fails to start pxc clusters.
Now, it's removed.

Remove equal sign from sed in DBaaS setup

---

docs/details/dashboards/index.md
docs/details/index.md
docs/how-to/configure.md
docs/how-to/index.md
docs/how-to/troubleshoot.md
docs/setting-up/client/index.md
docs/setting-up/index.md
docs/setting-up/server/docker.md
docs/using/alerting.md
docs/using/index.md
docs/using/platform/security-threat-tool.md
mkdocs.yml
requirements.txt

New plugin adds links to section headings (MkDocs doesn't do this by default). This recreates the behaviour of other PMM doc sites and the old Sphinx-based PMM2/PMM1 docs.
Section landing pages are also updated with commentary on subsections.

Index page links

---

docs/index.md
variables.yml

Begin making source less mkdocs-y. Use standard GH admonitions where possible, augmented with standard HTML bootstrap ones where needed.

Test mkdocs admonition alternatives

---

variables.yml

We had issues with disconnecting during ongoing queries. Operators team created custom build based on v1.7.0 but with the fix for the issues we were having.

Use custom PXC operator

---

docs/setting-up/client/postgresql.md

The package name seems incorrect.
Debian
```sh
$ apt list postgresql-contrib postgres-contrib
Listing... Done
postgresql-contrib/stable 11+200+deb10u4 all
N: There is 1 additional version. Please use the '-a' switch to see it
```
CentOS 7
```sh
$ yum info postgresql-contrib postgres-contrib                                                                                                                                       
Loaded plugins: changelog, product-id, search-disabled-repos, versionlock
Excluding 2 updates due to versionlock (use "yum versionlock status" to show them)
Available Packages
Name        : postgresql-contrib
Arch        : x86_64
Version     : 9.2.24
Release     : 4.el7_8
Size        : 552 k
Repo        : base/7/x86_64
Summary     : Extension modules distributed with …
```

Fixed package name for contrib

---

docs/using/alerting.md

https://jira.percona.com/browse/PMM-7700
This PR adds some more details on what users can use for their template parameters, such as types and units allowed.

PMM-7700: update template params' constraints

---

README.md
mkdocs-netlify.yml
mkdocs-pdf.yml
mkdocs.yml

Separated (again) mkdocs config for PDF generation. This makes build instructions easier as no config file editing is needed. The downside is the need to keep the `nav` element in sync.

Separate pdf config

---

docs/setting-up/server/dbaas.md
docs/using/platform/dbaas.md

Reverts percona/pmm-doc#452
It should be reverted, because secrets won't be required in the release 2.17.0

PMM-7927 Revert "PMM-7353 Remove secrets.yaml"

---

docs/setting-up/server/dbaas.md

We use HAProxy as a default proxy for PXC cluster instead of ProxySQL now.

PMM-7013 Use HAProxy instead of ProxySQL

---

docs/setting-up/client/mongodb.md

1. Added warning about `rateLimit` in a config file block.
2. Moved tips before examples. I think it's more natural because if you see examples you want to run it. 
3. Added link to `pmm-admin add mongodb`options.

Small improvement for mongodb agent docs

---

docs/setting-up/server/aws.md

A user on the forums interpreted this as a command they must run on a newly created PMM server from AWS Marketplace and broke their install badly!  Needed to clarify that is an example only for another DB host and should NOT be run on the PMM server.  Feel free to reword!

Feedback from forum user

---

docs/pmm-admin.md

The flags --SERVER_USER and --SERVER_PASSWORD (in uppercase letters) aren't accepted by the pmm-admin command in the last version of pmm-client v1. Although PMMv1 is not actively developed anymore in favor of PMMv2 at least make the documentation match with the CLI command.

pmm-admin command fails with unknown flag

---

docs/release-notes/2.20.0.md

Found the blurb about the issue starting in 2.16.0 to be confusing so tried to clarify it a bit more.  Since the two commands get the user back up and running I moved that up over a backup and restore since we gloss over that users may have installed their original image with a complex docker run command.

Updating instructions for 2.20.0 RN

---

.github/workflows/build.yml
docs/setting-up/server/easy-install.md

macOS 11.5 and Debian 11 both allow `shasum -a` option. Command change to use this approach to make a common code block.
https://deploy-preview-585--pmm-doc.netlify.app

Common Linux/macOS command for shasum

---

docs/setting-up/server/docker.md

While docker-compose is widely used internally, it's not an official and supported way of installing PMM.
We can have the instructions in forum or blogs but not in the official documentation as this is confusing

remove docker compose way from official Doc

---

docs/setting-up/client/aws.md

To enable QAN for a Postgres instance in Amazon RDS, pg_stat_statements needs to be enabled in postgres database on the server.

QAN in Amazon RDS Postgres uses postgres database

---

docs/using/interface.md

Remove default timezone "browser" in dashboards. Add describe how to change default users timezone.

PMM-9157: Add documentation for changing default timezone in Grafana.

---

docs/details/commands/pmm-admin.md

A new flag is added to pmm-admin. The '--paths-base' flag allows to pass base directory parameter to pmm-agent.

PMM 8972: Base path flag added to pmm-admin

---

docs/release-notes/2.25.0.md
docs/setting-up/server/docker.md

Removed reference to HTTP use as the way that was worded originally made it sound like if port 80 was enabled you should use that instead...

stop hinting at port 80 use!

---

docs/setting-up/server/virtual-appliance.md

this comes from a forum post and seems to be linked to this bug https://bugzilla.redhat.com/show_bug.cgi?id=1760806.  
I have tested this to work on 2.25.0's OVA with both network restart and machine restarts.

static IP preserving restarts

---

docs/setting-up/client/proxysql.md

* Updated username and password using `admin` to `pmm`, consistent with later examples
* Added note about using `admin-stats_credentials` to allow read-only access for the monitoring account
N.B. this is based upon the presumption that PMM does not need to be able to make changes to ProxySQL.

Suggest using a monitoring account

---

docs/release-notes/2.25.0.md
docs/release-notes/2.26.0.md

adding alert for docker way update to 2.25.0

docker-way upgrade without external access was broken for versions <= 2.23.0 (#684)

---

docs/how-to/troubleshoot.md
docs/setting-up/server/index.md

Use API keys as a replacement for basic authentication.

PMM-9670 using API key for authentication

---

docs/details/victoria-metrics.md

PMM can set the following flags that allow users to set all other VictoriaMetrics parameters as environment variables:
-envflag.enable 
-envflag.prefix=VM_. The environment variable must be prepended with VM_

PMM-9713 change victoriametrics parameters

---

.github/workflows/build.yml

This was failing for non-perconian contributors, so we are disaling it

PMM-7 don't push PRs to preview branch

---

docs/setting-up/client/postgresql.md

1. eliminate duplication
2. removed confusing text about  service id  (useless for the reader) and special node name (not possible when adding the Service)

PMM-10100 cleaning up instructions

---

docs/details/develop-checks/checks-v1.md
docs/details/develop-checks/checks-v2.md

As advisor check development isn't production ready, ensure there is a warning that the process should not be used in a production server and is for debugging/testing only.

Add note about production safety to check development

---

docs/release-notes/2.30.0.md

Correcting the names and versions
- PMM doesn't support MySQL Operator, only  PXC  based 
- mongoDB operator 1.11 was added in https://jira.percona.com/browse/PMM-9178  (pmm 2.27)

Correct name of the operator for pxc

---

docs/using/backup.md

This gives a sample user IAM policy for the minimum permissions needed for PMM backups to work.  I've also updated in the xtrabackup/xbcloud docs and will update this to cross-link once that goes live, but it will be some time until 8.0.30 is released.

Adding the S3 permissions PMM backups

---

docs/setting-up/client/postgresql.md

Included pg_stat_monitor.pgsm_enable_query_plan in the configuration section. 
Changed parameters link from github page to online percona.com documentation page.

Include variable for enabling query plans.

---

docs/using/backup.md

Follow-up of PR #917 & PR #916.
The net effect of these two PRs about MySQL supported setups was that we have two sections for MySQL.
This PR fixes the situation by:
- removing one duplicate section
- making sure S3-compatible is still mentioned
Thanks

Fix supported MySQL backup setups

---

docs/using/backup.md

As it was, from [link](https://pmm-doc-2-32-pr-923.onrender.com/using/backup.html#post-restore-requirements-for-mongodb):
After the fix:

Backup - fix wrongly formatted list

---

docs/using/mongodb_limitations.md

Remove a confusing line.
I wasn't able to understand what was that for. Perhaps something old?
I am sharing a screenshot below (see the highlighted text) from [link](https://docs.percona.com/percona-monitoring-and-management/using/mongodb_limitations.html). 
If this is not the correct fix, or if you have any context on the removed line, please let me know. Happy to change this PR.
Thanks
---

MongoDB Backup limitations - remove confusing line

---

docs/setting-up/server/docker.md

as is, the existing documentation won't work until you rename the old container.  This is the error you would get
```docker: Error response from daemon: Conflict. The container name "/pmm-server" is already in use by container "0270fbfd68911886f1121168e84fff95d067257761395b3e478b7409c3124a3e". You have to remove (or rename) that container to be able to reuse that name.```

Add docker rename step

---

docs/release-notes/2.31.0.md

Issue introduced by PR #929 (where the file was moved to "get-started" folder).

Fix alerting link in release notes

---

docs/how-to/configure.md

The link to public address section was broken

Fix broken link to public address

---

docs/get-started/alerting.md

This bullet was creating confusion with users thinking we were actively creating alert templates and shipping them according to tier but we've not started doing that yet.

Removed bullet point that was not true

---

docs/get-started/alerting.md

from ### Silences section: (before change proposal): "During a silence, PMM continues to track metrics and **trigger alerts** but does not send notifications to the specified contact points. Once the specified silence expires, notifications are resumed." The whole point of a silence is to stop alerts from triggering..pmm does continue to track metrics, but will NOT trigger any alerts if they are silenced (kinda defeats the whole purpose, no?) I have removed 'and trigger alerts'

removed the term 'trigger alerts'

---

docs/release-notes/2.37.1.md

Add RHEL9 migration as Technical Preview in the Release Notes, as this is confusing the users.

RN_Techpreview_RHEL9_2_37_0

---

docs/how-to/troubleshoot.md

For details see:
https://jira.percona.com/browse/PMM-12231

PMM- 12231 PMM disallows install remove plugins

---

docs/setting-up/client/mysql.md

since the user is created as: 'pmm'@'127.0.0.1'
if one tries to run the GRANT example it will fail due mismatch on the host:
```
mysql> GRANT SELECT, PROCESS, REPLICATION CLIENT, RELOAD, BACKUP_ADMIN ON *.* TO 'pmm'@'localhost';
ERROR 1410 (42000): You are not allowed to create a user with GRANT
```
hence, changing it to "127.0.0.1"

host changed on GRANT example

---

docs/details/commands/pmm-admin.md
docs/details/commands/pmm-agent.md

For details see,
https://jira.percona.com/browse/PMM-12422

PMM-12422-exporters-bind-push-mode

---

docs/setting-up/server/docker.md

Fix alignment of sibling items

---

docs/release-notes/2.42.0.md

v2.42.0 - Fix headings in release notes
